# Generated by Django 3.1.1 on 2020-09-18 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trafficapp', '0002_trafficgeneraterequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrafficRequest',
        ),
    ]
